name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install --upgrade build

      - run: python -m build
        working-directory: .

      - uses: pypa/gh-action-pypi-publish@v1.8.11
        working-directory: .
